### PR TITLE
fix drawing of ODs

### LINKED ISSUE #23: potential problem with "red edges"
The following instance surprised me a bit:
* [output-1.pdf](https://github.com/jvoigtlaender/alloy-cd-od/files/2918468/output-1.pdf)
* [output-2.pdf](https://github.com/jvoigtlaender/alloy-cd-od/files/2918471/output-2.pdf)
* [output-1not2-1.pdf](https://github.com/jvoigtlaender/alloy-cd-od/files/2918473/output-1not2-1.pdf)

Is everything legal here? Are there assumptions baked into the Alloy formalization that break down for cases with "red edges"? Should "red edges" be completely ruled out after all, even now that we print out link names (following https://github.com/jvoigtlaender/alloy-cd-od/pull/9)?

### PR DESCRIPTION
**Pull request by marcellussiegburg**
- close #23

### CODE REVIEW

**Comment by jvoigtlaender** [comment]
Does not seem to address the second bullet point from https://github.com/jvoigtlaender/alloy-cd-od/issues/23#issuecomment-468689179.

File: Output.hs [hunk 1]
```diff
@@ -69,15 +69,15 @@ drawOdFromInstance printNames input file format = do
   let theEdges = map ((\[from,v,to] -> (fromJust (elemIndex from theNodes), fromJust (elemIndex to theNodes), takeWhile (/= '$') v)) . splitOn "->") $
                  filter (not . null) (splitOn ", " (init (tail (fromJust (stripPrefix "this/Obj<:get=" objGetLine)))))
   let numberedNodes = zip [0..] theNodes
-  let graph = undir (mkGraph numberedNodes theEdges) :: Gr String String
+  let graph = mkGraph numberedNodes theEdges :: Gr String String
   objectNames <-
     map (\(i, l) -> (i, let [n,z] = splitOn "$" l in firstLower n ++ (if z == "0" then "" else z) ++ " "))
     <$> drop (length theNodes `div` 3)
     <$> shuffleM numberedNodes
   let dotGraph = setDirectedness graphToDot (nonClusteredParams {
```
Comment (jvoigtlaender) [inline Output.hs]: Should `setDirectedness` still be used now?
